config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users,
             path: "",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               sign_up: "register",
             }
  resources :projects, except: [:show] do
    put :sort, on: :collection
  end
  get "project/:id", to: "projects#show", as: "project_show"

  get "about-me", to: "pages#about"
  get "contact", to: "pages#contact"

  resources :blogs do
    member do
      post :toggle_status
    end
  end

  mount ActionCable.server => "/cable"

  root to: "pages#home"
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Qi Wu</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_generator("nav-link", "span") %>
      <%= login_helper("nav-link") %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_nav.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4">
      <div class="container">
        <span><%= link_to 'Write a New Blog', new_blog_path, class: "nav-link" if logged_in?(:site_admin) %></span>
        <span><%= link_to "Topics", topics_path, class: "nav-link" %></span>
      </div>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">Blogs</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <a class="text-muted" href="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
      </a>
      <div class="col-4 pt-1">
        <%= login_helper("text-muted") %>
      </div>
    </div>
  </div>
</header>

<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <%= nav_generator("p-2 text-muted", "span") %>
  </nav>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">Welcome</h4>
    <p class="mb-0">Thank you for your visit! I started my career as a structural Engineer, and made a transition
      to be a software development recently. I therefore would like share with you what I have learned along my way of
      becoming a professional software developer. I hope this is helpful to you.</p>
  </div>

  <div class="p-3">
    <h4>Topics</h4>
    <% @sidebar_topics.each do |t| %>
      <p><%= link_to t.title, topic_path(t) %></p>
    <% end%>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/qiwu7"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.instagram.com/qwu7777777"><%= fa_icon "instagram" %></a></li>
      <li><a href="https://www.facebook.com/michael.wu.7140497"><%= fa_icon "facebook" %></a></li>
      <li><a href="https://twitter.com/jimoswallowtail"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <%= link_to "Home", root_path %>
  <%= link_to "Blog", blogs_path %>
  <%= link_to "Portfolio", projects_path %>
  <%= link_to "About", about_me_path %>
  <%= link_to "Contact", contact_path %>
</div>

app/views/shared/_project_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "Back To All Projects", projects_path %> /
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_project_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Projects</h1>
    <p class="lead text-muted">Please take a look at the projects or works that I have been working on. </p>
    <p>
      <%= link_to "Find More About Me", about_me_path, class: "btn btn-primary" %>
      <%= link_to "My Blogs", blogs_path, class: "btn btn-secondary"  %>
    </p>
  </div>
</section>

app/views/shared/_project_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Nice To Meet You</h4>
          <p class="text-muted">你好 | 안녕하세요 | Bonjour | こんにちは | tere | здравей | cześć | hej | Hallo | Привет</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Expore</h4>
          <ul class="list-unstyled">
            <%= nav_generator("text-white", "li") %>
            <li><%= login_helper("text-white") %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Qi Wu</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>