config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users,
             path: "",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               sign_up: "register",
             }
  resources :projects, except: [:show] do
    put :sort, on: :collection
  end
  get "project/:id", to: "projects#show", as: "project_show"

  get "about-me", to: "pages#about"
  get "contact", to: "pages#contact"

  resources :blogs do
    member do
      post :toggle_status
    end
  end

  mount ActionCable.server => "/cable"

  root to: "pages#home"
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :thumb_image, ProjectUploader
  mount_uploader :main_image, ProjectUploader

  has_many :technologies

  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs[:name].blank? }

  validates_presence_of :title, :body

  scope :by_position, -> { order(:position) }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project_item, only: [:edit, :update, :show, :destroy]
  layout "project"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :edit, :update, :sort]}, site_admin: :all

  def index
    @project_items = Project.by_position
  end

  def sort
    params[:order].each do |k, v|
      Project.find(v[:id]).update!(position: v[:position])
    end

    render nothing: true
  end

  def new
    @project_item = Project.new
  end

  def create
    @project_item = Project.new(project_params)

    respond_to do |format|
      if @project_item.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @project_item.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    # destroy/delete record
    @project_item.destroy

    # redirect
    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Project was successfully destroyed.' }
    end
  end

  private

  def project_params
    params.require(:project).permit(
      :title,
      :subtitle,
      :body,
      :main_image,
      :thumb_image,
      technologies_attributes: [:id, :name, :_destroy],
    )
  end

  def set_project_item
    @project_item = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def image_generator(height:, width:)
    "https://placehold.it/#{height}x#{width}"
  end

  def project_img(img, type)
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == "thumb"
      image_generator(height: "350", width: "200")
    elsif type == "main"
      image_generator(height: "600", width: "400")
    end
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project_item) do |form| %>
  <% if @project_item.errors.any? %>
    <%= @project_item.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <h3>Basic Info</h3>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: "form-control" %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file
          <%= form.file_field :main_image, style: 'display:none' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file
          <%= form.file_field :thumb_image, style: 'display:none' %>

        </label>
      </div>

      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control", rows: 10 %>
      </div>
    </div>
    <div class="col-md-6">
      <h3>Technology Used:</h3>
      <div>
        <%= form.fields_for :technologies do |technology_form| %>
          <%= render "technology_fields", f: technology_form %>
        <% end %>

        <div>
          <%= link_to_add_association "Add Technology", form, :technologies %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <%= form.submit "Save Project Item", class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
<% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/_project_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 box-shadow", data-id="<%= project_item.id %>">
    <%= image_tag project_img(project_item.thumb_image, "thumb"), width: "100%" %>
    <div class="card-body">
      <p class="card-text">
        <span><%= link_to project_item.title, project_show_path(project_item) %></span> [<%= project_item.subtitle %>]
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <a href="<%= project_show_path(project_item) %>">
            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
          </a>
          <% if logged_in?(:site_admin) %>
            <a href="<%= edit_project_path(project_item) %>">
              <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
            </a>
          <% end %>
        </div>
        <small class="text-muted">9 mins</small>
      </div>
    </div>
  </div>
</div>

app/views/projects/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association "Remove Technology", f %>
</div>

app/views/projects/edit.html.erb
<div class="container project-container">
  <h1>Edit a new Project Item</h1>
  <hr>
  <%= render "form", project_item: @project_item %>
</div>

app/views/projects/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= link_to "Create New Item", new_project_url if logged_in?(:site_admin) %>

    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: "project_item", collection: @project_items %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container project-container">
  <h1>Create a new Project Item</h1>
  <hr>
  <%= render "form", project_item: @project_item %>
</div>

app/views/projects/show.html.erb
<div class="container project-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag project_img(@project_item.main_image, "main"), width: "100%" %>
    </div>
    <div class="col-md-5">
      <h1><%= @project_item.title %></h1>
      <hr>
      <em><%= @project_item.subtitle %></em>
      <p><%=  @project_item.body %></p>
      <hr>
      <h3>Technologies Used:</h3>
      <% @project_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div>
          <%= link_to "Edit Item", edit_project_path(@project_item), class: "btn btn-warning" %>
        </div>
      <% end %>
    </div>
  </div>
</div>